-- CreateEnum
CREATE TYPE "ProductCategory" AS ENUM ('ELECTRONICS', 'CLOTHING', 'FURNITURE', 'BOOKS', 'TOYS', 'SPORTS', 'BEAUTY', 'HEALTH', 'GROCERY', 'HOME_APPLIANCES', 'OTHER');

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "category" "ProductCategory" NOT NULL DEFAULT 'OTHER';
